name: Build

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      tag-name:
        type: string
        default: "draft"
      channel:
        type: string
        default: "dev"
  workflow_dispatch:

env:
  IS_GITHUB_ACTIONS: 1
  CHANNEL: "${{ inputs.channel }}"
  FLUTTER_VERSION: '3.24.0'
  UPLOAD_ARTIFACT: "${{ inputs.upload-artifact }}"
  TAG_NAME: "${{ inputs.tag-name }}"
  TARGET_NAME_apk: "Hiddify-Android"
  TARGET_NAME_exe: "Hiddify-Windows-x64"
  TARGET_NAME_dmg: "Hiddify-MacOS"
  TARGET_NAME_pkg: "Hiddify-MacOS-Installer"
  TARGET_NAME_ipa: "Hiddify-iOS"
  TARGET_NAME_AppImage: "Hiddify-Linux-x64"
  TARGET_NAME_deb: "Hiddify-Debian-x64"
  TARGET_NAME_rpm: "Hiddify-rpm-x64"

jobs:
  build_ios:
    permissions: write-all
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
  
      - name: Clean Flutter Build
        run: |
          flutter clean
  
      - name: Get Flutter Packages
        run: |
          flutter pub get
  
      - name: Reinstall iOS Dependencies
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install
          
      - name: Install tree
        run: brew install tree

      - name: Prepare for iOS
        run: |
          make ios-prepare
          tree
  
      - name: Build iOS (No Code Sign)
        run: |
          flutter build ipa --no-codesign
  
      - name: Copy to out iOS
        run: |
          mkdir out
          mv build/ios/ipa/*.ipa out/${TARGET_NAME_ipa}.ipa
  
      - name: Upload iOS Artifact
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: iOS
          path: ./out
          retention-days: 1
